#!/bin/bash

# Cap CPU (and GPU where supported) max frequency to keep the machine cool/quiet.
# Installs a root-owned helper and a root cron job that re-applies the cap every
# 5 minutes (some drivers reset it on resume / power-source changes), then runs
# it once immediately.
#
# GPU handling is driver-aware:
#   amdgpu -> power_dpm_force_performance_level = low
#   i915   -> cap gt_max_freq_mhz to GPU_INTEL_PERCENT% of hardware max (RP0)
#   xe     -> cap per-tile/gt max_freq to GPU_INTEL_PERCENT% of rp0_freq
#   other  -> best-effort devfreq clamp (ARM: panfrost/mali/lima/…)

set -e

CPU_MAX_KHZ=3000000                       # per-core scaling_max_freq cap (3.0 GHz)
GPU_INTEL_PERCENT=70                       # Intel GPU max cap, % of hardware max
HELPER=/usr/local/sbin/limit-cpu-gpu-freq.sh
CRON_LINE="*/5 * * * * $HELPER"

if [[ "$EUID" == 0 ]]; then
    echo "Please run as normal user (w/o sudo)"
    exit
fi

term_color_red () {
    echo -e "\e[91m"
}

term_color_white () {
    echo -e "\e[39m"
}

detect_gpu(){
    for d in /sys/class/drm/card[0-9]*/device/driver; do
        [[ -e $d ]] || continue
        basename "$(readlink -f "$d")"
        return
    done
    echo "unknown"
}

confirmation(){
    term_color_red
    echo "This will:"
    echo "  - install $HELPER"
    echo "  - add a root cron job:  $CRON_LINE"
    echo "  - cap each CPU core to  $((CPU_MAX_KHZ / 1000)) MHz"
    echo "  - lower the GPU where supported (detected driver: $(detect_gpu))"
    echo "    (Intel GPUs capped to ${GPU_INTEL_PERCENT}% of max; amdgpu forced to 'low')"
    echo
    echo "Proceed? (y/n)"
    term_color_white

    echo
    read -n 1 ans
    echo

    if [[ ! $ans == "y" ]]; then
        echo ""
        exit 1
    fi
}

install_helper(){
    term_color_red
    echo "Install $HELPER"
    term_color_white

    # Written with a quoted heredoc (no expansion here); CPU_MAX_KHZ is patched
    # in afterwards so the helper is self-contained when cron runs it as root.
    sudo tee "$HELPER" > /dev/null <<'EOF'
#!/bin/bash
# Auto-generated by 61_cpu_gpu_low_freq_cron_rule.sh -- do not edit by hand.
# Cap CPU and GPU max frequency. Runs as root (cron / manual).

CPU_MAX_KHZ=__CPU_MAX_KHZ__
GPU_INTEL_PERCENT=__GPU_INTEL_PERCENT__

# Return PERCENT% of $1, but never below the floor $2 (both integers).
pct_of(){
    local val=$(( $1 * GPU_INTEL_PERCENT / 100 ))
    (( val < $2 )) && val=$2
    echo "$val"
}

# --- CPU: clamp every core's scaling_max_freq ---
for f in /sys/devices/system/cpu/cpu*/cpufreq/scaling_max_freq; do
    [[ -w $f ]] || continue
    echo "$CPU_MAX_KHZ" > "$f" 2>/dev/null || true
done

# --- GPU: driver-aware clamp ---
gpu_driver(){
    for d in /sys/class/drm/card[0-9]*/device/driver; do
        [[ -e $d ]] || continue
        basename "$(readlink -f "$d")"
        return
    done
    echo unknown
}

case "$(gpu_driver)" in
amdgpu)
    for f in /sys/class/drm/card[0-9]*/device/power_dpm_force_performance_level; do
        [[ -w $f ]] || continue
        echo low > "$f" 2>/dev/null || true
    done
    ;;
i915)
    # Cap max to GPU_INTEL_PERCENT% of hardware max (RP0), floored at RPn.
    for c in /sys/class/drm/card[0-9]*; do
        max=$c/gt_max_freq_mhz
        [[ -w $max && -r $c/gt_RP0_freq_mhz ]] || continue
        rp0=$(cat "$c/gt_RP0_freq_mhz")
        if [[ -r $c/gt_RPn_freq_mhz ]]; then floor=$(cat "$c/gt_RPn_freq_mhz")
        else floor=0; fi
        cap=$(pct_of "$rp0" "$floor")
        echo "$cap" > "$max" 2>/dev/null || true
    done
    ;;
xe)
    # Newer Intel Xe: per-tile/gt freq knobs.
    for max in /sys/class/drm/card[0-9]*/device/tile*/gt*/freq*/max_freq; do
        [[ -w $max ]] || continue
        d=${max%/max_freq}
        [[ -r $d/rp0_freq ]] || continue
        rp0=$(cat "$d/rp0_freq")
        if [[ -r $d/rpn_freq ]]; then floor=$(cat "$d/rpn_freq")
        else floor=0; fi
        cap=$(pct_of "$rp0" "$floor")
        echo "$cap" > "$max" 2>/dev/null || true
    done
    ;;
*)
    # ARM / others: best-effort devfreq clamp.
    for max in /sys/class/devfreq/*/max_freq; do
        [[ -w $max ]] || continue
        d=${max%/max_freq}
        if   [[ -r $d/min_freq ]]; then
            cap=$(cat "$d/min_freq")
        elif [[ -r $d/available_frequencies ]]; then
            cap=$(tr ' ' '\n' < "$d/available_frequencies" | sort -n | head -n1)
        else cap=""; fi
        [[ -n $cap ]] && { echo "$cap" > "$max" 2>/dev/null || true; }
    done
    ;;
esac
EOF

    sudo sed -i "s/__CPU_MAX_KHZ__/$CPU_MAX_KHZ/" "$HELPER"
    sudo sed -i "s/__GPU_INTEL_PERCENT__/$GPU_INTEL_PERCENT/" "$HELPER"
    sudo chown root:root "$HELPER"
    sudo chmod 755 "$HELPER"
}

install_cron(){
    term_color_red
    echo "Install root cron job"
    term_color_white

    # Idempotent: drop any existing line for this helper, then append ours.
    {
        sudo crontab -l 2>/dev/null | grep -vF "$HELPER" || true
        echo "$CRON_LINE"
    } | sudo crontab -
}

apply_now(){
    term_color_red
    echo "Apply once now"
    term_color_white

    sudo "$HELPER"
}

post(){
    term_color_red
    echo "Done"
    echo "- helper:  $HELPER"
    echo "- cron:    $CRON_LINE  (root)"
    echo "- CPU cap: $((CPU_MAX_KHZ / 1000)) MHz per core"
    echo "- verify:  cpu-check / gpu-check   (see shrc aliases)"
    echo "- to undo: sudo crontab -e (remove the line), sudo rm $HELPER,"
    echo "           then reboot to restore default frequencies"
    term_color_white
}

trap term_color_white EXIT
confirmation
install_helper
install_cron
apply_now
post
