#!/bin/bash

# Pin the wired/wireless NICs to stable names (eth0 / wlan0) by MAC address.
# Detects the first en*/wl* interface, writes a persistent-net udev rule and
# reloads udev. The rename itself takes effect on the next reboot.

set -e

RULE_FILE=/etc/udev/rules.d/70-persistent-net.rules

if [[ "$EUID" == 0 ]]; then
    echo "Please run as normal user (w/o sudo)"
    exit
fi

term_color_red () {
    echo -e "\e[91m"
}

term_color_white () {
    echo -e "\e[39m"
}

# First wired / wireless interface (predictable names en*/wl*).
ENO=$(ls /sys/class/net | grep -E '^en' | head -n1)
WLP=$(ls /sys/class/net | grep -E '^wl' | head -n1)

confirmation(){
    term_color_red
    echo "Detected interfaces:"
    [[ -n $ENO ]] && echo "  wired:    $ENO ($(cat /sys/class/net/$ENO/address)) -> eth0"
    [[ -n $WLP ]] && echo "  wireless: $WLP ($(cat /sys/class/net/$WLP/address)) -> wlan0"
    if [[ -z $ENO && -z $WLP ]]; then
        echo "  none found (no en*/wl* device)"
        term_color_white
        exit 1
    fi
    echo
    echo "Write $RULE_FILE and reload udev? (y/n)"
    term_color_white

    echo
    read -n 1 ans
    echo

    if [[ ! $ans == "y" ]]; then
        echo ""
        exit 1
    fi
}

write_rule(){
    term_color_red
    echo "Writing $RULE_FILE"
    term_color_white

    {
        echo "# Generated by 90_get_network_udev_rule.sh"
        if [[ -n $ENO ]]; then
            MAC=$(cat /sys/class/net/$ENO/address)
            echo "SUBSYSTEM==\"net\", ACTION==\"add\", DRIVERS==\"?*\", ATTR{address}==\"$MAC\", ATTR{dev_id}==\"0x0\", ATTR{type}==\"1\", NAME=\"eth0\""
        fi
        if [[ -n $WLP ]]; then
            MAC=$(cat /sys/class/net/$WLP/address)
            echo "SUBSYSTEM==\"net\", ACTION==\"add\", DRIVERS==\"?*\", ATTR{address}==\"$MAC\", KERNEL==\"wlan*\", NAME=\"wlan0\""
        fi
    } | sudo tee "$RULE_FILE" > /dev/null
}

apply(){
    term_color_red
    echo "Reloading udev rules"
    term_color_white

    sudo udevadm control --reload-rules
}

post(){
    term_color_red
    echo "Done"
    echo "- rule written to $RULE_FILE"
    echo "- reboot for the eth0 / wlan0 rename to take effect"
    term_color_white
}

trap term_color_white EXIT
confirmation
write_rule
apply
post
